<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <Version>0.1.11-windows8</Version>
    <AssemblyVersion>0.1.11.0</AssemblyVersion>
    <FileVersion>0.1.11.0</FileVersion>
    <ManagedWimLibVersion>2.5.3</ManagedWimLibVersion>
  </PropertyGroup>
</Project>
