<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ESDInstaller.Windows7.Core</AssemblyName>
    <RootNamespace>ESDInstaller.Windows7.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Udf" Version="0.16.13" />
    <PackageReference Include="ManagedWimLib" Version="2.6.0" />
    <Reference Include="System.Management" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
</Project>
